-- 코드를 입력하세요
SELECT i.NAME, i.DATETIME
FROM ANIMAL_INS i
WHERE i.ANIMAL_ID NOT IN (
    SELECT i.ANIMAL_ID i
    FROM ANIMAL_INS i
    JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
)
ORDER BY DATETIME
LIMIT 3