-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P
JOIN APPOINTMENT A ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE '2022-04-13%'
ORDER BY A.APNT_YMD ASC