-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
    JOIN
        (SELECT BOARD_ID
                ,RANK() OVER (ORDER BY VIEWS DESC) RNK
        FROM USED_GOODS_BOARD) AS VIEWS_RNK
    ON F.BOARD_ID = VIEWS_RNK.BOARD_ID
WHERE VIEWS_RNK.RNK = 1
ORDER BY F.FILE_ID DESC
;